# lang_config.py
# -*- coding: utf-8 -*-

LANGUAGES = {
    "中文": {
        "title": "Moho 脚本管理器",
        "select_folder": "💼 选择 'Scripts' 文件夹",
        "open_folder": "📂 打开 'Scripts' 文件夹",
        "add_folder": "📦 导入脚本",
        "refresh": "🔄 刷新列表",
        "select_all": "☑️ 全选",
        "deselect_all": "⬜ 取消全选",
        "del_selected": "🗑 删除选中项",
        "sort_az": "👀 文件名 (A-Z)",
        "sort_za": "👀 文件名 (Z-A)",
        "sort_time": "👀 修改日期 (最新)",
        "list_label": "脚本列表 (Scripts/Tool)",
        "no_folder": "请先选择 'Scripts' 文件夹...",
        "error_folder_name": "选择错误",
        "error_folder_msg": "请选择名为 'Scripts' 的文件夹！\n你当前选择的是: {path}",
        "confirm_del_title": "删除警告",
        "confirm_del_msg": "你即将删除 {count} 个脚本。\n\n⚠️ 注意：以下关联资源将一并被彻底删除：\n\n{deps}\n\n确定要继续吗？",
        "del_no_selection": "未选择任何脚本。",
        "dep_del_yes": "确认删除",
        "dep_del_no": "我再想想",
        "delete_success_msg": "已成功删除 {count} 个脚本。",
        "import_success_msg": "扫描完成。\n共发现并导入了 {count} 个脚本。",
        "import_title": "导入完成",
        "import_err": "在选中的文件夹中未发现 Tool / ScriptResources / Utility 文件夹。",
        "link_scripts": "📜 Moho Scripts",
        "author": "by 萌酥33",
        "error": "错误"
    },
    "繁体中文": {
        "title": "Moho 腳本管理器",
        "select_folder": "💼 選擇 'Scripts' 資料夾",
        "open_folder": "📂 開啟 'Scripts' 資料夾",
        "add_folder": "📦 匯入腳本",
        "refresh": "🔄 重新整理",
        "select_all": "☑️ 全選",
        "deselect_all": "⬜ 取消全選",
        "del_selected": "🗑 刪除選取項目",
        "sort_az": "👀 檔名 (A-Z)",
        "sort_za": "👀 檔名 (Z-A)",
        "sort_time": "👀 修改日期 (最新)",
        "list_label": "腳本列表 (Scripts/Tool)",
        "no_folder": "請先選擇 'Scripts' 資料夾...",
        "error_folder_name": "選擇錯誤",
        "error_folder_msg": "請選擇名為 'Scripts' 的資料夾！\n你目前選擇的是: {path}",
        "confirm_del_title": "刪除警告",
        "confirm_del_msg": "你即將刪除 {count} 個腳本。\n\n⚠️ 注意：以下關聯資源將一併被徹底刪除：\n\n{deps}\n\n確定要繼續嗎？",
        "del_no_selection": "未選擇任何腳本。",
        "dep_del_yes": "確認刪除",
        "dep_del_no": "我再想想",
        "delete_success_msg": "已成功刪除 {count} 個腳本。",
        "import_success_msg": "掃描完成。\n共發現並匯入了 {count} 個腳本。",
        "import_title": "匯入完成",
        "import_err": "在選取的資料夾中未發現 Tool / ScriptResources / Utility 資料夾。",
        "link_scripts": "📜 Moho Scripts",
        "author": "by 萌酥33",
        "error": "錯誤"
    },
    "English": {
        "title": "Moho Script Manager",
        "select_folder": "💼 Select 'Scripts' Folder",
        "open_folder": "📂 Open 'Scripts' Folder",
        "add_folder": "📦 Import Scripts",
        "refresh": "🔄 Refresh List",
        "select_all": "☑️ Select All",
        "deselect_all": "⬜ Deselect All",
        "del_selected": "🗑 Delete Selected",
        "sort_az": "👀 Name (A-Z)",
        "sort_za": "👀 Name (Z-A)",
        "sort_time": "👀 Date Modified (Newest)",
        "list_label": "Script List (Scripts/Tool)",
        "no_folder": "Please select 'Scripts' folder first...",
        "error_folder_name": "Selection Error",
        "error_folder_msg": "Please select the folder named 'Scripts'!\nYou selected: {path}",
        "confirm_del_title": "Delete Warning",
        "confirm_del_msg": "You are about to delete {count} scripts.\n\n⚠️ Warning: The following associated resources will also be permanently deleted:\n\n{deps}\n\nAre you sure you want to continue?",
        "del_no_selection": "No scripts selected.",
        "dep_del_yes": "Yes, Delete",
        "dep_del_no": "Cancel",
        "delete_success_msg": "Successfully deleted {count} items.",
        "import_success_msg": "Scan complete.\nFound and imported {count} scripts.",
        "import_title": "Import Complete",
        "import_err": "No Tool / ScriptResources / Utility folders found in the selected directory.",
        "link_scripts": "📜 Moho Scripts",
        "author": "by MoeU33",
        "error": "Error"
    },
    "Русский": {
        "title": "Менеджер скриптов Moho",
        "select_folder": "💼 Выбрать папку 'Scripts'",
        "open_folder": "📂 Открыть папку 'Scripts'",
        "add_folder": "📦 Импорт скриптов",
        "refresh": "🔄 Обновить",
        "select_all": "☑️ Выбрать все",
        "deselect_all": "⬜ Снять выделение",
        "del_selected": "🗑 Удалить выбранное",
        "sort_az": "👀 Имя (A-Z)",
        "sort_za": "👀 Имя (Z-A)",
        "sort_time": "👀 Дата (Сначала новые)",
        "list_label": "Список скриптов (Scripts/Tool)",
        "no_folder": "Сначала выберите папку 'Scripts'...",
        "error_folder_name": "Ошибка выбора",
        "error_folder_msg": "Пожалуйста, выберите папку с именем 'Scripts'!\nВы выбрали: {path}",
        "confirm_del_title": "Предупреждение об удалении",
        "confirm_del_msg": "Вы собираетесь удалить {count} скриптов.\n\n⚠️ Внимание: Следующие связанные ресурсы также будут безвозвратно удалены:\n\n{deps}\n\nПродолжить?",
        "del_no_selection": "Скрипты не выбраны.",
        "dep_del_yes": "Удалить",
        "dep_del_no": "Отмена",
        "delete_success_msg": "Успешно удалено {count} элементов.",
        "import_success_msg": "Сканирование завершено.\nНайдено и импортировано {count} скриптов.",
        "import_title": "Импорт завершен",
        "import_err": "В выбранной папке не найдены папки Tool / ScriptResources / Utility.",
        "link_scripts": "📜 Moho Scripts",
        "author": "by MoeU33",
        "error": "Ошибка"
    },
    "Español": {
        "title": "Gestor de Scripts de Moho",
        "select_folder": "💼 Seleccionar carpeta 'Scripts'",
        "open_folder": "📂 Abrir carpeta 'Scripts'",
        "add_folder": "📦 Importar Scripts",
        "refresh": "🔄 Actualizar",
        "select_all": "☑️ Seleccionar todo",
        "deselect_all": "⬜ Deseleccionar todo",
        "del_selected": "🗑 Eliminar seleccionados",
        "sort_az": "👀 Nombre (A-Z)",
        "sort_za": "👀 Nombre (Z-A)",
        "sort_time": "👀 Fecha (Más reciente)",
        "list_label": "Lista de Scripts (Scripts/Tool)",
        "no_folder": "Por favor seleccione la carpeta 'Scripts'...",
        "error_folder_name": "Error de selección",
        "error_folder_msg": "¡Por favor seleccione la carpeta llamada 'Scripts'!\nSeleccionó: {path}",
        "confirm_del_title": "Advertencia de eliminación",
        "confirm_del_msg": "Está a punto de eliminar {count} scripts.\n\n⚠️ Advertencia: Los siguientes recursos asociados también serán eliminados permanentemente:\n\n{deps}\n\n¿Desea continuar?",
        "del_no_selection": "No hay scripts seleccionados.",
        "dep_del_yes": "Sí, eliminar",
        "dep_del_no": "Cancelar",
        "delete_success_msg": "Se eliminaron {count} elementos con éxito.",
        "import_success_msg": "Escaneo completo.\nSe encontraron e importaron {count} scripts.",
        "import_title": "Importación completa",
        "import_err": "No se encontraron carpetas Tool / ScriptResources / Utility en el directorio seleccionado.",
        "link_scripts": "📜 Moho Scripts",
        "author": "by MoeU33",
        "error": "Error"
    },
    "日本語": {
        "title": "Moho スクリプトマネージャー",
        "select_folder": "💼 'Scripts' フォルダを選択",
        "open_folder": "📂 'Scripts' フォルダを開く",
        "add_folder": "📦 スクリプトをインポート",
        "refresh": "🔄 更新",
        "select_all": "☑️ 全て選択",
        "deselect_all": "⬜ 選択解除",
        "del_selected": "🗑 選択項目を削除",
        "sort_az": "👀 名前 (A-Z)",
        "sort_za": "👀 名前 (Z-A)",
        "sort_time": "👀 更新日時 (新しい順)",
        "list_label": "スクリプト一覧 (Scripts/Tool)",
        "no_folder": "'Scripts' フォルダを選択してください...",
        "error_folder_name": "選択エラー",
        "error_folder_msg": "'Scripts' という名前のフォルダを選択してください！\n現在の選択: {path}",
        "confirm_del_title": "削除の警告",
        "confirm_del_msg": "{count} 個のスクリプトを削除しようとしています。\n\n⚠️ 注意：以下の関連リソースも完全に削除されます：\n\n{deps}\n\n続けてもよろしいですか？",
        "del_no_selection": "スクリプトが選択されていません。",
        "dep_del_yes": "削除する",
        "dep_del_no": "キャンセル",
        "delete_success_msg": "{count} 個の項目を正常に削除しました。",
        "import_success_msg": "スキャン完了。\n{count} 個のスクリプトが見つかり、インポートされました。",
        "import_title": "インポート完了",
        "import_err": "選択したフォルダ内に Tool / ScriptResources / Utility フォルダが見つかりませんでした。",
        "link_scripts": "📜 Moho Scripts",
        "author": "by MoeU33",
        "error": "エラー"
    },
    "한국어": {
        "title": "Moho 스크립트 관리자",
        "select_folder": "💼 'Scripts' 폴더 선택",
        "open_folder": "📂 'Scripts' 폴더 열기",
        "add_folder": "📦 스크립트 가져오기",
        "refresh": "🔄 목록 새로고침",
        "select_all": "☑️ 전체 선택",
        "deselect_all": "⬜ 선택 해제",
        "del_selected": "🗑 선택 항목 삭제",
        "sort_az": "👀 이름 (A-Z)",
        "sort_za": "👀 이름 (Z-A)",
        "sort_time": "👀 수정한 날짜 (최신순)",
        "list_label": "스크립트 목록 (Scripts/Tool)",
        "no_folder": "먼저 'Scripts' 폴더를 선택하세요...",
        "error_folder_name": "선택 오류",
        "error_folder_msg": "'Scripts' 라는 이름의 폴더를 선택해주세요!\n현재 선택: {path}",
        "confirm_del_title": "삭제 경고",
        "confirm_del_msg": "{count} 개의 스크립트를 삭제하려고 합니다.\n\n⚠️ 주의: 다음 관련 리소스도 함께 영구적으로 삭제됩니다:\n\n{deps}\n\n계속하시겠습니까?",
        "del_no_selection": "선택된 스크립트가 없습니다.",
        "dep_del_yes": "삭제 확인",
        "dep_del_no": "취소",
        "delete_success_msg": "{count} 개의 항목이 성공적으로 삭제되었습니다.",
        "import_success_msg": "스캔 완료.\n{count} 개의 스크립트를 찾아 가져왔습니다.",
        "import_title": "가져오기 완료",
        "import_err": "선택한 폴더에서 Tool / ScriptResources / Utility 폴더를 찾을 수 없습니다.",
        "link_scripts": "📜 Moho Scripts",
        "author": "by MoeU33",
        "error": "오류"
    }
}

def get_lang(lang_code):
    if lang_code not in LANGUAGES:
        return LANGUAGES["English"]
    return LANGUAGES[lang_code]